name: CI (Go)

on:
  push:
  workflow_dispatch:

concurrency:
  group: ci-go-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Build Runner
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2.3.4

      - name: Build Runner
        run: make
        working-directory: runner
