name: Code Style Check

on:
  push:
  workflow_dispatch:

concurrency:
  group: csc-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  codestyle:
    name: Run code style check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out source code
        uses: actions/checkout@v4.2.2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@3.1.1

      - name: Add error matcher
        run: echo "::add-matcher::$(pwd)/.github/checkstyle-problem-matcher.json"

      - name: Run style check
        run: vendor/bin/phpcs --report=checkstyle
